services:
  - type: web
    name: portafolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portafolioweb.wsgi:application
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portafolio-db
          property: connectionString
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: vcelir2@unemi.edu.ec
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin123
    postDeployCommand: |
      python manage.py migrate
      python manage.py createsuperuser --noinput || echo "Superuser ya existe"
